### ISSUE TITLE
daises

### ISSUE THREAD

**Issue by netcrave** [dongrote/mrtheplague#2]
tulips

**Comment by eacmen** [comment]
Did you run it through the pre-processor?

**Comment by netcrave** [comment]
YES! come to my channel on efnet and lets see if we can figure this out there, #netcrave

**Comment by eacmen** [comment]
What is there to figure out? Unit tests passed. Conversation over.

**Comment by eacmen** [comment]
/SUMMON not supported, you must be at least 12 years old to use this integration.

**Comment by netcrave** [comment]
OH DONT GET ME WRONG, the mentality I am running is on fucking point. My game is strong

**Comment by netcrave** [comment]
I've been on some hardchats for like more than a fucking minute
